# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-24 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MW', '0003_auto_20160624_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='pub_date',
            field=models.DateTimeField(),
        ),
    ]
