# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-24 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MW', '0004_auto_20160624_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='value',
            old_name='pub_date',
            new_name='pubDate',
        ),
    ]
